# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'obdscanner.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QDial, QDialogButtonBox,
    QFrame, QLCDNumber, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QRadioButton, QScrollArea, QSizePolicy, QTabWidget,
    QTextEdit, QToolButton, QWidget)

class Ui_OBDScanner(object):
    def setupUi(self, OBDScanner):
        if not OBDScanner.objectName():
            OBDScanner.setObjectName(u"OBDScanner")
        OBDScanner.resize(684, 399)
        self.actionQuit = QAction(OBDScanner)
        self.actionQuit.setObjectName(u"actionQuit")
        self.centralWidget = QWidget(OBDScanner)
        self.centralWidget.setObjectName(u"centralWidget")
        self.btRadioButton = QRadioButton(self.centralWidget)
        self.btRadioButton.setObjectName(u"btRadioButton")
        self.btRadioButton.setGeometry(QRect(10, 10, 96, 23))
        self.btRadioButton.setChecked(True)
        self.btConfigButton = QToolButton(self.centralWidget)
        self.btConfigButton.setObjectName(u"btConfigButton")
        self.btConfigButton.setGeometry(QRect(100, 10, 24, 24))
        self.label = QLabel(self.centralWidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(140, 10, 81, 17))
        self.connectedDeviceName = QLabel(self.centralWidget)
        self.connectedDeviceName.setObjectName(u"connectedDeviceName")
        self.connectedDeviceName.setGeometry(QRect(230, 10, 131, 17))
        self.tabWidget = QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(10, 50, 661, 301))
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.rtd_tab = QWidget()
        self.rtd_tab.setObjectName(u"rtd_tab")
        self.speed_dial = QDial(self.rtd_tab)
        self.speed_dial.setObjectName(u"speed_dial")
        self.speed_dial.setEnabled(True)
        self.speed_dial.setGeometry(QRect(30, 80, 131, 131))
        self.speed_dial.setMouseTracking(False)
        self.speed_dial.setFocusPolicy(Qt.WheelFocus)
        self.speed_dial.setAcceptDrops(False)
        self.speed_dial.setAutoFillBackground(True)
        self.speed_dial.setMaximum(230)
        self.speed_dial.setPageStep(5)
        self.speed_dial.setSliderPosition(0)
        self.speed_dial.setTracking(True)
        self.speed_dial.setInvertedAppearance(False)
        self.speed_dial.setInvertedControls(False)
        self.speed_dial.setWrapping(False)
        self.speed_dial.setNotchesVisible(True)
        self.speedLcd = QLCDNumber(self.rtd_tab)
        self.speedLcd.setObjectName(u"speedLcd")
        self.speedLcd.setGeometry(QRect(70, 30, 64, 23))
        self.rpmLcd = QLCDNumber(self.rtd_tab)
        self.rpmLcd.setObjectName(u"rpmLcd")
        self.rpmLcd.setGeometry(QRect(220, 40, 64, 23))
        self.label_2 = QLabel(self.rtd_tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(190, 10, 131, 20))
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.rtd_tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 10, 121, 20))
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(self.rtd_tab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(350, 10, 131, 20))
        self.label_4.setAlignment(Qt.AlignCenter)
        self.inTempLcd = QLCDNumber(self.rtd_tab)
        self.inTempLcd.setObjectName(u"inTempLcd")
        self.inTempLcd.setGeometry(QRect(380, 40, 64, 23))
        self.label_5 = QLabel(self.rtd_tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(510, 10, 131, 20))
        self.label_5.setAlignment(Qt.AlignCenter)
        self.coolantLcd = QLCDNumber(self.rtd_tab)
        self.coolantLcd.setObjectName(u"coolantLcd")
        self.coolantLcd.setGeometry(QRect(540, 30, 64, 23))
        self.coolant_dial = QDial(self.rtd_tab)
        self.coolant_dial.setObjectName(u"coolant_dial")
        self.coolant_dial.setEnabled(True)
        self.coolant_dial.setGeometry(QRect(510, 80, 131, 131))
        self.coolant_dial.setMouseTracking(False)
        self.coolant_dial.setFocusPolicy(Qt.WheelFocus)
        self.coolant_dial.setAcceptDrops(False)
        self.coolant_dial.setAutoFillBackground(True)
        self.coolant_dial.setMinimum(-20)
        self.coolant_dial.setMaximum(150)
        self.coolant_dial.setPageStep(5)
        self.coolant_dial.setValue(-20)
        self.coolant_dial.setSliderPosition(-20)
        self.coolant_dial.setTracking(True)
        self.coolant_dial.setOrientation(Qt.Horizontal)
        self.coolant_dial.setInvertedAppearance(False)
        self.coolant_dial.setInvertedControls(False)
        self.coolant_dial.setWrapping(False)
        self.coolant_dial.setNotchesVisible(True)
        self.intake_dial = QDial(self.rtd_tab)
        self.intake_dial.setObjectName(u"intake_dial")
        self.intake_dial.setEnabled(True)
        self.intake_dial.setGeometry(QRect(350, 80, 131, 131))
        self.intake_dial.setMouseTracking(False)
        self.intake_dial.setFocusPolicy(Qt.WheelFocus)
        self.intake_dial.setAcceptDrops(False)
        self.intake_dial.setAutoFillBackground(True)
        self.intake_dial.setMinimum(-40)
        self.intake_dial.setMaximum(130)
        self.intake_dial.setPageStep(5)
        self.intake_dial.setValue(-40)
        self.intake_dial.setSliderPosition(-40)
        self.intake_dial.setTracking(True)
        self.intake_dial.setInvertedAppearance(False)
        self.intake_dial.setInvertedControls(False)
        self.intake_dial.setWrapping(False)
        self.intake_dial.setNotchesVisible(True)
        self.rpm_dial = QDial(self.rtd_tab)
        self.rpm_dial.setObjectName(u"rpm_dial")
        self.rpm_dial.setEnabled(True)
        self.rpm_dial.setGeometry(QRect(190, 80, 131, 131))
        self.rpm_dial.setMouseTracking(False)
        self.rpm_dial.setFocusPolicy(Qt.WheelFocus)
        self.rpm_dial.setAcceptDrops(False)
        self.rpm_dial.setAutoFillBackground(True)
        self.rpm_dial.setMaximum(9000)
        self.rpm_dial.setSingleStep(1)
        self.rpm_dial.setPageStep(100)
        self.rpm_dial.setSliderPosition(0)
        self.rpm_dial.setTracking(True)
        self.rpm_dial.setInvertedAppearance(False)
        self.rpm_dial.setInvertedControls(False)
        self.rpm_dial.setWrapping(False)
        self.rpm_dial.setNotchesVisible(True)
        self.label_6 = QLabel(self.rtd_tab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(60, 230, 71, 17))
        self.label_6.setLayoutDirection(Qt.LeftToRight)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(self.rtd_tab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(220, 230, 71, 17))
        self.label_7.setLayoutDirection(Qt.LeftToRight)
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.rtd_tab)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(380, 230, 71, 17))
        self.label_8.setLayoutDirection(Qt.LeftToRight)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.rtd_tab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(540, 230, 71, 17))
        self.label_9.setLayoutDirection(Qt.LeftToRight)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.rtd_startButton = QPushButton(self.rtd_tab)
        self.rtd_startButton.setObjectName(u"rtd_startButton")
        self.rtd_startButton.setGeometry(QRect(0, 10, 31, 25))
        self.tabWidget.addTab(self.rtd_tab, "")
        self.dtc_tab = QWidget()
        self.dtc_tab.setObjectName(u"dtc_tab")
        self.scrollArea = QScrollArea(self.dtc_tab)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(10, 10, 631, 241))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 629, 239))
        self.dtc_checkErrNumberButton = QPushButton(self.scrollAreaWidgetContents)
        self.dtc_checkErrNumberButton.setObjectName(u"dtc_checkErrNumberButton")
        self.dtc_checkErrNumberButton.setGeometry(QRect(400, 10, 131, 25))
        self.dtc_getErrCodesButton = QPushButton(self.scrollAreaWidgetContents)
        self.dtc_getErrCodesButton.setObjectName(u"dtc_getErrCodesButton")
        self.dtc_getErrCodesButton.setGeometry(QRect(400, 50, 131, 25))
        self.dtc_clearErrors = QPushButton(self.scrollAreaWidgetContents)
        self.dtc_clearErrors.setObjectName(u"dtc_clearErrors")
        self.dtc_clearErrors.setGeometry(QRect(400, 90, 131, 25))
        self.dtc_numberEdit = QLineEdit(self.scrollAreaWidgetContents)
        self.dtc_numberEdit.setObjectName(u"dtc_numberEdit")
        self.dtc_numberEdit.setGeometry(QRect(160, 10, 71, 25))
        self.label_10 = QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 10, 141, 21))
        self.label_11 = QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 50, 171, 21))
        self.dtc_descriptionEdit = QTextEdit(self.scrollAreaWidgetContents)
        self.dtc_descriptionEdit.setObjectName(u"dtc_descriptionEdit")
        self.dtc_descriptionEdit.setGeometry(QRect(10, 80, 341, 151))
        self.dtc_milIndicatorON = QRadioButton(self.scrollAreaWidgetContents)
        self.dtc_milIndicatorON.setObjectName(u"dtc_milIndicatorON")
        self.dtc_milIndicatorON.setEnabled(False)
        self.dtc_milIndicatorON.setGeometry(QRect(240, 10, 111, 23))
        self.dtc_confirmatioFrame = QFrame(self.scrollAreaWidgetContents)
        self.dtc_confirmatioFrame.setObjectName(u"dtc_confirmatioFrame")
        self.dtc_confirmatioFrame.setEnabled(False)
        self.dtc_confirmatioFrame.setGeometry(QRect(370, 120, 191, 80))
        self.dtc_confirmatioFrame.setFrameShape(QFrame.StyledPanel)
        self.dtc_confirmatioFrame.setFrameShadow(QFrame.Raised)
        self.dtc_confirmationBox = QDialogButtonBox(self.dtc_confirmatioFrame)
        self.dtc_confirmationBox.setObjectName(u"dtc_confirmationBox")
        self.dtc_confirmationBox.setEnabled(False)
        self.dtc_confirmationBox.setGeometry(QRect(10, 50, 166, 25))
        self.dtc_confirmationBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.dtc_confirmationBox.setCenterButtons(False)
        self.label_12 = QLabel(self.dtc_confirmatioFrame)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 10, 91, 20))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.dtc_tab, "")
        self.cmd_tab = QWidget()
        self.cmd_tab.setObjectName(u"cmd_tab")
        self.cmd_sendButton = QPushButton(self.cmd_tab)
        self.cmd_sendButton.setObjectName(u"cmd_sendButton")
        self.cmd_sendButton.setGeometry(QRect(450, 220, 71, 25))
        self.cmd_input = QLineEdit(self.cmd_tab)
        self.cmd_input.setObjectName(u"cmd_input")
        self.cmd_input.setGeometry(QRect(10, 220, 431, 25))
        self.cmd_console = QTextEdit(self.cmd_tab)
        self.cmd_console.setObjectName(u"cmd_console")
        self.cmd_console.setGeometry(QRect(10, 10, 601, 201))
        self.cmd_console.setTabChangesFocus(False)
        self.cmd_console.setReadOnly(True)
        self.cmd_clearButton = QPushButton(self.cmd_tab)
        self.cmd_clearButton.setObjectName(u"cmd_clearButton")
        self.cmd_clearButton.setGeometry(QRect(540, 220, 71, 25))
        self.tabWidget.addTab(self.cmd_tab, "")
        self.widget = QWidget()
        self.widget.setObjectName(u"widget")
        self.widget.setEnabled(False)
        font = QFont()
        font.setKerning(True)
        self.widget.setFont(font)
        self.tabWidget.addTab(self.widget, "")
        OBDScanner.setCentralWidget(self.centralWidget)
        self.menuBar = QMenuBar(OBDScanner)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 684, 22))
        self.menuOBDScanner = QMenu(self.menuBar)
        self.menuOBDScanner.setObjectName(u"menuOBDScanner")
        OBDScanner.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menuOBDScanner.menuAction())
        self.menuOBDScanner.addAction(self.actionQuit)

        self.retranslateUi(OBDScanner)
        self.actionQuit.triggered.connect(OBDScanner.close)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(OBDScanner)
    # setupUi

    def retranslateUi(self, OBDScanner):
        OBDScanner.setWindowTitle(QCoreApplication.translate("OBDScanner", u"OBDScanner", None))
        self.actionQuit.setText(QCoreApplication.translate("OBDScanner", u"&Quit", None))
        self.btRadioButton.setText(QCoreApplication.translate("OBDScanner", u"Bluetooth", None))
        self.btConfigButton.setText(QCoreApplication.translate("OBDScanner", u"...", None))
        self.label.setText(QCoreApplication.translate("OBDScanner", u"Connected to:", None))
        self.connectedDeviceName.setText("")
        self.label_2.setText(QCoreApplication.translate("OBDScanner", u"RPM", None))
        self.label_3.setText(QCoreApplication.translate("OBDScanner", u"Speed", None))
        self.label_4.setText(QCoreApplication.translate("OBDScanner", u"Intake temp.", None))
        self.label_5.setText(QCoreApplication.translate("OBDScanner", u"Coolant temp.", None))
        self.label_6.setText(QCoreApplication.translate("OBDScanner", u"km/h", None))
        self.label_7.setText(QCoreApplication.translate("OBDScanner", u"r/min", None))
        self.label_8.setText(QCoreApplication.translate("OBDScanner", u"<html><head/><body><p><span style=\" vertical-align:super;\">o</span>C</p></body></html>", None))
        self.label_9.setText(QCoreApplication.translate("OBDScanner", u"<html><head/><body><p><span style=\" vertical-align:super;\">o</span>C</p></body></html>", None))
        self.rtd_startButton.setText(QCoreApplication.translate("OBDScanner", u"Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rtd_tab), QCoreApplication.translate("OBDScanner", u"RTD", None))
        self.dtc_checkErrNumberButton.setText(QCoreApplication.translate("OBDScanner", u"Check error number", None))
        self.dtc_getErrCodesButton.setText(QCoreApplication.translate("OBDScanner", u"Get error codes", None))
        self.dtc_clearErrors.setText(QCoreApplication.translate("OBDScanner", u"Clear errors", None))
        self.label_10.setText(QCoreApplication.translate("OBDScanner", u"Number of error codes:", None))
        self.label_11.setText(QCoreApplication.translate("OBDScanner", u"Diagnostic Trouble Codes :", None))
        self.dtc_milIndicatorON.setText(QCoreApplication.translate("OBDScanner", u"&MIL turned on", None))
        self.label_12.setText(QCoreApplication.translate("OBDScanner", u"Are You sure ?", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dtc_tab), QCoreApplication.translate("OBDScanner", u"DTC", None))
        self.cmd_sendButton.setText(QCoreApplication.translate("OBDScanner", u"send", None))
        self.cmd_clearButton.setText(QCoreApplication.translate("OBDScanner", u"clear", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cmd_tab), QCoreApplication.translate("OBDScanner", u"CMD console", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), QCoreApplication.translate("OBDScanner", u"Info", None))
        self.menuOBDScanner.setTitle(QCoreApplication.translate("OBDScanner", u"OBDSca&nner", None))
    # retranslateUi

