package com.google.android.gms.internal.mlkit_vision_barcode;

import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import java.io.IOException;

/* compiled from: com.google.android.gms:play-services-mlkit-barcode-scanning@@16.2.0 */
final class zzgg implements ObjectEncoder<zzjf> {
    private static final FieldDescriptor zzA;
    private static final FieldDescriptor zzB;
    private static final FieldDescriptor zzC;
    private static final FieldDescriptor zzD;
    private static final FieldDescriptor zzE;
    private static final FieldDescriptor zzF;
    private static final FieldDescriptor zzG;
    private static final FieldDescriptor zzH;
    private static final FieldDescriptor zzI;
    private static final FieldDescriptor zzJ;
    private static final FieldDescriptor zzK;
    private static final FieldDescriptor zzL;
    private static final FieldDescriptor zzM;
    private static final FieldDescriptor zzN;
    private static final FieldDescriptor zzO;
    private static final FieldDescriptor zzP;
    private static final FieldDescriptor zzQ;
    private static final FieldDescriptor zzR;
    private static final FieldDescriptor zzS;
    private static final FieldDescriptor zzT;
    private static final FieldDescriptor zzU;
    private static final FieldDescriptor zzV;
    private static final FieldDescriptor zzW;
    private static final FieldDescriptor zzX;
    private static final FieldDescriptor zzY;
    private static final FieldDescriptor zzZ;
    static final zzgg zza = new zzgg();
    private static final FieldDescriptor zzaa;
    private static final FieldDescriptor zzab;
    private static final FieldDescriptor zzac;
    private static final FieldDescriptor zzad;
    private static final FieldDescriptor zzae;
    private static final FieldDescriptor zzaf;
    private static final FieldDescriptor zzb;
    private static final FieldDescriptor zzc;
    private static final FieldDescriptor zzd;
    private static final FieldDescriptor zze;
    private static final FieldDescriptor zzf;
    private static final FieldDescriptor zzg;
    private static final FieldDescriptor zzh;
    private static final FieldDescriptor zzi;
    private static final FieldDescriptor zzj;
    private static final FieldDescriptor zzk;
    private static final FieldDescriptor zzl;
    private static final FieldDescriptor zzm;
    private static final FieldDescriptor zzn;
    private static final FieldDescriptor zzo;
    private static final FieldDescriptor zzp;
    private static final FieldDescriptor zzq;
    private static final FieldDescriptor zzr;
    private static final FieldDescriptor zzs;
    private static final FieldDescriptor zzt;
    private static final FieldDescriptor zzu;
    private static final FieldDescriptor zzv;
    private static final FieldDescriptor zzw;
    private static final FieldDescriptor zzx;
    private static final FieldDescriptor zzy;
    private static final FieldDescriptor zzz;

    static {
        FieldDescriptor.Builder builder = FieldDescriptor.builder("systemInfo");
        zzcw zzcw = new zzcw();
        zzcw.zza(1);
        zzb = builder.withProperty(zzcw.zzb()).build();
        FieldDescriptor.Builder builder2 = FieldDescriptor.builder("eventName");
        zzcw zzcw2 = new zzcw();
        zzcw2.zza(2);
        zzc = builder2.withProperty(zzcw2.zzb()).build();
        FieldDescriptor.Builder builder3 = FieldDescriptor.builder("isThickClient");
        zzcw zzcw3 = new zzcw();
        zzcw3.zza(37);
        zzd = builder3.withProperty(zzcw3.zzb()).build();
        FieldDescriptor.Builder builder4 = FieldDescriptor.builder("modelDownloadLogEvent");
        zzcw zzcw4 = new zzcw();
        zzcw4.zza(3);
        zze = builder4.withProperty(zzcw4.zzb()).build();
        FieldDescriptor.Builder builder5 = FieldDescriptor.builder("customModelLoadLogEvent");
        zzcw zzcw5 = new zzcw();
        zzcw5.zza(20);
        zzf = builder5.withProperty(zzcw5.zzb()).build();
        FieldDescriptor.Builder builder6 = FieldDescriptor.builder("customModelInferenceLogEvent");
        zzcw zzcw6 = new zzcw();
        zzcw6.zza(4);
        zzg = builder6.withProperty(zzcw6.zzb()).build();
        FieldDescriptor.Builder builder7 = FieldDescriptor.builder("customModelCreateLogEvent");
        zzcw zzcw7 = new zzcw();
        zzcw7.zza(29);
        zzh = builder7.withProperty(zzcw7.zzb()).build();
        FieldDescriptor.Builder builder8 = FieldDescriptor.builder("onDeviceFaceDetectionLogEvent");
        zzcw zzcw8 = new zzcw();
        zzcw8.zza(5);
        zzi = builder8.withProperty(zzcw8.zzb()).build();
        FieldDescriptor.Builder builder9 = FieldDescriptor.builder("onDeviceFaceLoadLogEvent");
        zzcw zzcw9 = new zzcw();
        zzcw9.zza(59);
        zzj = builder9.withProperty(zzcw9.zzb()).build();
        FieldDescriptor.Builder builder10 = FieldDescriptor.builder("onDeviceTextDetectionLogEvent");
        zzcw zzcw10 = new zzcw();
        zzcw10.zza(6);
        zzk = builder10.withProperty(zzcw10.zzb()).build();
        FieldDescriptor.Builder builder11 = FieldDescriptor.builder("onDeviceBarcodeDetectionLogEvent");
        zzcw zzcw11 = new zzcw();
        zzcw11.zza(7);
        zzl = builder11.withProperty(zzcw11.zzb()).build();
        FieldDescriptor.Builder builder12 = FieldDescriptor.builder("onDeviceBarcodeLoadLogEvent");
        zzcw zzcw12 = new zzcw();
        zzcw12.zza(58);
        zzm = builder12.withProperty(zzcw12.zzb()).build();
        FieldDescriptor.Builder builder13 = FieldDescriptor.builder("onDeviceImageLabelCreateLogEvent");
        zzcw zzcw13 = new zzcw();
        zzcw13.zza(48);
        zzn = builder13.withProperty(zzcw13.zzb()).build();
        FieldDescriptor.Builder builder14 = FieldDescriptor.builder("onDeviceImageLabelLoadLogEvent");
        zzcw zzcw14 = new zzcw();
        zzcw14.zza(49);
        zzo = builder14.withProperty(zzcw14.zzb()).build();
        FieldDescriptor.Builder builder15 = FieldDescriptor.builder("onDeviceImageLabelDetectionLogEvent");
        zzcw zzcw15 = new zzcw();
        zzcw15.zza(18);
        zzp = builder15.withProperty(zzcw15.zzb()).build();
        FieldDescriptor.Builder builder16 = FieldDescriptor.builder("onDeviceObjectCreateLogEvent");
        zzcw zzcw16 = new zzcw();
        zzcw16.zza(26);
        zzq = builder16.withProperty(zzcw16.zzb()).build();
        FieldDescriptor.Builder builder17 = FieldDescriptor.builder("onDeviceObjectLoadLogEvent");
        zzcw zzcw17 = new zzcw();
        zzcw17.zza(27);
        zzr = builder17.withProperty(zzcw17.zzb()).build();
        FieldDescriptor.Builder builder18 = FieldDescriptor.builder("onDeviceObjectInferenceLogEvent");
        zzcw zzcw18 = new zzcw();
        zzcw18.zza(28);
        zzs = builder18.withProperty(zzcw18.zzb()).build();
        FieldDescriptor.Builder builder19 = FieldDescriptor.builder("onDevicePoseDetectionLogEvent");
        zzcw zzcw19 = new zzcw();
        zzcw19.zza(44);
        zzt = builder19.withProperty(zzcw19.zzb()).build();
        FieldDescriptor.Builder builder20 = FieldDescriptor.builder("onDeviceSegmentationLogEvent");
        zzcw zzcw20 = new zzcw();
        zzcw20.zza(45);
        zzu = builder20.withProperty(zzcw20.zzb()).build();
        FieldDescriptor.Builder builder21 = FieldDescriptor.builder("onDeviceSmartReplyLogEvent");
        zzcw zzcw21 = new zzcw();
        zzcw21.zza(19);
        zzv = builder21.withProperty(zzcw21.zzb()).build();
        FieldDescriptor.Builder builder22 = FieldDescriptor.builder("onDeviceLanguageIdentificationLogEvent");
        zzcw zzcw22 = new zzcw();
        zzcw22.zza(21);
        zzw = builder22.withProperty(zzcw22.zzb()).build();
        FieldDescriptor.Builder builder23 = FieldDescriptor.builder("onDeviceTranslationLogEvent");
        zzcw zzcw23 = new zzcw();
        zzcw23.zza(22);
        zzx = builder23.withProperty(zzcw23.zzb()).build();
        FieldDescriptor.Builder builder24 = FieldDescriptor.builder("cloudFaceDetectionLogEvent");
        zzcw zzcw24 = new zzcw();
        zzcw24.zza(8);
        zzy = builder24.withProperty(zzcw24.zzb()).build();
        FieldDescriptor.Builder builder25 = FieldDescriptor.builder("cloudCropHintDetectionLogEvent");
        zzcw zzcw25 = new zzcw();
        zzcw25.zza(9);
        zzz = builder25.withProperty(zzcw25.zzb()).build();
        FieldDescriptor.Builder builder26 = FieldDescriptor.builder("cloudDocumentTextDetectionLogEvent");
        zzcw zzcw26 = new zzcw();
        zzcw26.zza(10);
        zzA = builder26.withProperty(zzcw26.zzb()).build();
        FieldDescriptor.Builder builder27 = FieldDescriptor.builder("cloudImagePropertiesDetectionLogEvent");
        zzcw zzcw27 = new zzcw();
        zzcw27.zza(11);
        zzB = builder27.withProperty(zzcw27.zzb()).build();
        FieldDescriptor.Builder builder28 = FieldDescriptor.builder("cloudImageLabelDetectionLogEvent");
        zzcw zzcw28 = new zzcw();
        zzcw28.zza(12);
        zzC = builder28.withProperty(zzcw28.zzb()).build();
        FieldDescriptor.Builder builder29 = FieldDescriptor.builder("cloudLandmarkDetectionLogEvent");
        zzcw zzcw29 = new zzcw();
        zzcw29.zza(13);
        zzD = builder29.withProperty(zzcw29.zzb()).build();
        FieldDescriptor.Builder builder30 = FieldDescriptor.builder("cloudLogoDetectionLogEvent");
        zzcw zzcw30 = new zzcw();
        zzcw30.zza(14);
        zzE = builder30.withProperty(zzcw30.zzb()).build();
        FieldDescriptor.Builder builder31 = FieldDescriptor.builder("cloudSafeSearchDetectionLogEvent");
        zzcw zzcw31 = new zzcw();
        zzcw31.zza(15);
        zzF = builder31.withProperty(zzcw31.zzb()).build();
        FieldDescriptor.Builder builder32 = FieldDescriptor.builder("cloudTextDetectionLogEvent");
        zzcw zzcw32 = new zzcw();
        zzcw32.zza(16);
        zzG = builder32.withProperty(zzcw32.zzb()).build();
        FieldDescriptor.Builder builder33 = FieldDescriptor.builder("cloudWebSearchDetectionLogEvent");
        zzcw zzcw33 = new zzcw();
        zzcw33.zza(17);
        zzH = builder33.withProperty(zzcw33.zzb()).build();
        FieldDescriptor.Builder builder34 = FieldDescriptor.builder("automlImageLabelingCreateLogEvent");
        zzcw zzcw34 = new zzcw();
        zzcw34.zza(23);
        zzI = builder34.withProperty(zzcw34.zzb()).build();
        FieldDescriptor.Builder builder35 = FieldDescriptor.builder("automlImageLabelingLoadLogEvent");
        zzcw zzcw35 = new zzcw();
        zzcw35.zza(24);
        zzJ = builder35.withProperty(zzcw35.zzb()).build();
        FieldDescriptor.Builder builder36 = FieldDescriptor.builder("automlImageLabelingInferenceLogEvent");
        zzcw zzcw36 = new zzcw();
        zzcw36.zza(25);
        zzK = builder36.withProperty(zzcw36.zzb()).build();
        FieldDescriptor.Builder builder37 = FieldDescriptor.builder("isModelDownloadedLogEvent");
        zzcw zzcw37 = new zzcw();
        zzcw37.zza(39);
        zzL = builder37.withProperty(zzcw37.zzb()).build();
        FieldDescriptor.Builder builder38 = FieldDescriptor.builder("deleteModelLogEvent");
        zzcw zzcw38 = new zzcw();
        zzcw38.zza(40);
        zzM = builder38.withProperty(zzcw38.zzb()).build();
        FieldDescriptor.Builder builder39 = FieldDescriptor.builder("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzcw zzcw39 = new zzcw();
        zzcw39.zza(30);
        zzN = builder39.withProperty(zzcw39.zzb()).build();
        FieldDescriptor.Builder builder40 = FieldDescriptor.builder("aggregatedCustomModelInferenceLogEvent");
        zzcw zzcw40 = new zzcw();
        zzcw40.zza(31);
        zzO = builder40.withProperty(zzcw40.zzb()).build();
        FieldDescriptor.Builder builder41 = FieldDescriptor.builder("aggregatedOnDeviceFaceDetectionLogEvent");
        zzcw zzcw41 = new zzcw();
        zzcw41.zza(32);
        zzP = builder41.withProperty(zzcw41.zzb()).build();
        FieldDescriptor.Builder builder42 = FieldDescriptor.builder("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzcw zzcw42 = new zzcw();
        zzcw42.zza(33);
        zzQ = builder42.withProperty(zzcw42.zzb()).build();
        FieldDescriptor.Builder builder43 = FieldDescriptor.builder("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzcw zzcw43 = new zzcw();
        zzcw43.zza(34);
        zzR = builder43.withProperty(zzcw43.zzb()).build();
        FieldDescriptor.Builder builder44 = FieldDescriptor.builder("aggregatedOnDeviceObjectInferenceLogEvent");
        zzcw zzcw44 = new zzcw();
        zzcw44.zza(35);
        zzS = builder44.withProperty(zzcw44.zzb()).build();
        FieldDescriptor.Builder builder45 = FieldDescriptor.builder("aggregatedOnDeviceTextDetectionLogEvent");
        zzcw zzcw45 = new zzcw();
        zzcw45.zza(36);
        zzT = builder45.withProperty(zzcw45.zzb()).build();
        FieldDescriptor.Builder builder46 = FieldDescriptor.builder("aggregatedOnDevicePoseDetectionLogEvent");
        zzcw zzcw46 = new zzcw();
        zzcw46.zza(46);
        zzU = builder46.withProperty(zzcw46.zzb()).build();
        FieldDescriptor.Builder builder47 = FieldDescriptor.builder("aggregatedOnDeviceSegmentationLogEvent");
        zzcw zzcw47 = new zzcw();
        zzcw47.zza(47);
        zzV = builder47.withProperty(zzcw47.zzb()).build();
        FieldDescriptor.Builder builder48 = FieldDescriptor.builder("remoteConfigLogEvent");
        zzcw zzcw48 = new zzcw();
        zzcw48.zza(42);
        zzW = builder48.withProperty(zzcw48.zzb()).build();
        FieldDescriptor.Builder builder49 = FieldDescriptor.builder("inputImageConstructionLogEvent");
        zzcw zzcw49 = new zzcw();
        zzcw49.zza(50);
        zzX = builder49.withProperty(zzcw49.zzb()).build();
        FieldDescriptor.Builder builder50 = FieldDescriptor.builder("leakedHandleEvent");
        zzcw zzcw50 = new zzcw();
        zzcw50.zza(51);
        zzY = builder50.withProperty(zzcw50.zzb()).build();
        FieldDescriptor.Builder builder51 = FieldDescriptor.builder("cameraSourceLogEvent");
        zzcw zzcw51 = new zzcw();
        zzcw51.zza(52);
        zzZ = builder51.withProperty(zzcw51.zzb()).build();
        FieldDescriptor.Builder builder52 = FieldDescriptor.builder("imageLabelOptionalModuleLogEvent");
        zzcw zzcw52 = new zzcw();
        zzcw52.zza(53);
        zzaa = builder52.withProperty(zzcw52.zzb()).build();
        FieldDescriptor.Builder builder53 = FieldDescriptor.builder("languageIdentificationOptionalModuleLogEvent");
        zzcw zzcw53 = new zzcw();
        zzcw53.zza(54);
        zzab = builder53.withProperty(zzcw53.zzb()).build();
        FieldDescriptor.Builder builder54 = FieldDescriptor.builder("faceDetectionOptionalModuleLogEvent");
        zzcw zzcw54 = new zzcw();
        zzcw54.zza(60);
        zzac = builder54.withProperty(zzcw54.zzb()).build();
        FieldDescriptor.Builder builder55 = FieldDescriptor.builder("nlClassifierOptionalModuleLogEvent");
        zzcw zzcw55 = new zzcw();
        zzcw55.zza(55);
        zzad = builder55.withProperty(zzcw55.zzb()).build();
        FieldDescriptor.Builder builder56 = FieldDescriptor.builder("nlClassifierClientLibraryLogEvent");
        zzcw zzcw56 = new zzcw();
        zzcw56.zza(56);
        zzae = builder56.withProperty(zzcw56.zzb()).build();
        FieldDescriptor.Builder builder57 = FieldDescriptor.builder("accelerationAllowlistLogEvent");
        zzcw zzcw57 = new zzcw();
        zzcw57.zza(57);
        zzaf = builder57.withProperty(zzcw57.zzb()).build();
    }

    private zzgg() {
    }

    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) throws IOException {
        zzjf zzjf = (zzjf) obj;
        ObjectEncoderContext objectEncoderContext = (ObjectEncoderContext) obj2;
        objectEncoderContext.add(zzb, (Object) zzjf.zze());
        objectEncoderContext.add(zzc, (Object) zzjf.zzb());
        objectEncoderContext.add(zzd, (Object) zzjf.zzf());
        objectEncoderContext.add(zze, (Object) null);
        objectEncoderContext.add(zzf, (Object) null);
        objectEncoderContext.add(zzg, (Object) null);
        objectEncoderContext.add(zzh, (Object) null);
        objectEncoderContext.add(zzi, (Object) null);
        objectEncoderContext.add(zzj, (Object) null);
        objectEncoderContext.add(zzk, (Object) null);
        objectEncoderContext.add(zzl, (Object) zzjf.zzc());
        objectEncoderContext.add(zzm, (Object) zzjf.zzd());
        objectEncoderContext.add(zzn, (Object) null);
        objectEncoderContext.add(zzo, (Object) null);
        objectEncoderContext.add(zzp, (Object) null);
        objectEncoderContext.add(zzq, (Object) null);
        objectEncoderContext.add(zzr, (Object) null);
        objectEncoderContext.add(zzs, (Object) null);
        objectEncoderContext.add(zzt, (Object) null);
        objectEncoderContext.add(zzu, (Object) null);
        objectEncoderContext.add(zzv, (Object) null);
        objectEncoderContext.add(zzw, (Object) null);
        objectEncoderContext.add(zzx, (Object) null);
        objectEncoderContext.add(zzy, (Object) null);
        objectEncoderContext.add(zzz, (Object) null);
        objectEncoderContext.add(zzA, (Object) null);
        objectEncoderContext.add(zzB, (Object) null);
        objectEncoderContext.add(zzC, (Object) null);
        objectEncoderContext.add(zzD, (Object) null);
        objectEncoderContext.add(zzE, (Object) null);
        objectEncoderContext.add(zzF, (Object) null);
        objectEncoderContext.add(zzG, (Object) null);
        objectEncoderContext.add(zzH, (Object) null);
        objectEncoderContext.add(zzI, (Object) null);
        objectEncoderContext.add(zzJ, (Object) null);
        objectEncoderContext.add(zzK, (Object) null);
        objectEncoderContext.add(zzL, (Object) null);
        objectEncoderContext.add(zzM, (Object) null);
        objectEncoderContext.add(zzN, (Object) null);
        objectEncoderContext.add(zzO, (Object) null);
        objectEncoderContext.add(zzP, (Object) null);
        objectEncoderContext.add(zzQ, (Object) zzjf.zza());
        objectEncoderContext.add(zzR, (Object) null);
        objectEncoderContext.add(zzS, (Object) null);
        objectEncoderContext.add(zzT, (Object) null);
        objectEncoderContext.add(zzU, (Object) null);
        objectEncoderContext.add(zzV, (Object) null);
        objectEncoderContext.add(zzW, (Object) null);
        objectEncoderContext.add(zzX, (Object) null);
        objectEncoderContext.add(zzY, (Object) null);
        objectEncoderContext.add(zzZ, (Object) null);
        objectEncoderContext.add(zzaa, (Object) null);
        objectEncoderContext.add(zzab, (Object) null);
        objectEncoderContext.add(zzac, (Object) null);
        objectEncoderContext.add(zzad, (Object) null);
        objectEncoderContext.add(zzae, (Object) null);
        objectEncoderContext.add(zzaf, (Object) null);
    }
}
