package com.google.android.gms.internal.mlkit_vision_text;

import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import java.io.IOException;

/* compiled from: com.google.android.gms:play-services-mlkit-text-recognition@@16.3.0 */
final class zzfw implements ObjectEncoder<zziv> {
    private static final FieldDescriptor zzA;
    private static final FieldDescriptor zzB;
    private static final FieldDescriptor zzC;
    private static final FieldDescriptor zzD;
    private static final FieldDescriptor zzE;
    private static final FieldDescriptor zzF;
    private static final FieldDescriptor zzG;
    private static final FieldDescriptor zzH;
    private static final FieldDescriptor zzI;
    private static final FieldDescriptor zzJ;
    private static final FieldDescriptor zzK;
    private static final FieldDescriptor zzL;
    private static final FieldDescriptor zzM;
    private static final FieldDescriptor zzN;
    private static final FieldDescriptor zzO;
    private static final FieldDescriptor zzP;
    private static final FieldDescriptor zzQ;
    private static final FieldDescriptor zzR;
    private static final FieldDescriptor zzS;
    private static final FieldDescriptor zzT;
    private static final FieldDescriptor zzU;
    private static final FieldDescriptor zzV;
    private static final FieldDescriptor zzW;
    private static final FieldDescriptor zzX;
    private static final FieldDescriptor zzY;
    private static final FieldDescriptor zzZ;
    static final zzfw zza = new zzfw();
    private static final FieldDescriptor zzaa;
    private static final FieldDescriptor zzab;
    private static final FieldDescriptor zzac;
    private static final FieldDescriptor zzad;
    private static final FieldDescriptor zzae;
    private static final FieldDescriptor zzaf;
    private static final FieldDescriptor zzb;
    private static final FieldDescriptor zzc;
    private static final FieldDescriptor zzd;
    private static final FieldDescriptor zze;
    private static final FieldDescriptor zzf;
    private static final FieldDescriptor zzg;
    private static final FieldDescriptor zzh;
    private static final FieldDescriptor zzi;
    private static final FieldDescriptor zzj;
    private static final FieldDescriptor zzk;
    private static final FieldDescriptor zzl;
    private static final FieldDescriptor zzm;
    private static final FieldDescriptor zzn;
    private static final FieldDescriptor zzo;
    private static final FieldDescriptor zzp;
    private static final FieldDescriptor zzq;
    private static final FieldDescriptor zzr;
    private static final FieldDescriptor zzs;
    private static final FieldDescriptor zzt;
    private static final FieldDescriptor zzu;
    private static final FieldDescriptor zzv;
    private static final FieldDescriptor zzw;
    private static final FieldDescriptor zzx;
    private static final FieldDescriptor zzy;
    private static final FieldDescriptor zzz;

    static {
        FieldDescriptor.Builder builder = FieldDescriptor.builder("systemInfo");
        zzcm zzcm = new zzcm();
        zzcm.zza(1);
        zzb = builder.withProperty(zzcm.zzb()).build();
        FieldDescriptor.Builder builder2 = FieldDescriptor.builder("eventName");
        zzcm zzcm2 = new zzcm();
        zzcm2.zza(2);
        zzc = builder2.withProperty(zzcm2.zzb()).build();
        FieldDescriptor.Builder builder3 = FieldDescriptor.builder("isThickClient");
        zzcm zzcm3 = new zzcm();
        zzcm3.zza(37);
        zzd = builder3.withProperty(zzcm3.zzb()).build();
        FieldDescriptor.Builder builder4 = FieldDescriptor.builder("modelDownloadLogEvent");
        zzcm zzcm4 = new zzcm();
        zzcm4.zza(3);
        zze = builder4.withProperty(zzcm4.zzb()).build();
        FieldDescriptor.Builder builder5 = FieldDescriptor.builder("customModelLoadLogEvent");
        zzcm zzcm5 = new zzcm();
        zzcm5.zza(20);
        zzf = builder5.withProperty(zzcm5.zzb()).build();
        FieldDescriptor.Builder builder6 = FieldDescriptor.builder("customModelInferenceLogEvent");
        zzcm zzcm6 = new zzcm();
        zzcm6.zza(4);
        zzg = builder6.withProperty(zzcm6.zzb()).build();
        FieldDescriptor.Builder builder7 = FieldDescriptor.builder("customModelCreateLogEvent");
        zzcm zzcm7 = new zzcm();
        zzcm7.zza(29);
        zzh = builder7.withProperty(zzcm7.zzb()).build();
        FieldDescriptor.Builder builder8 = FieldDescriptor.builder("onDeviceFaceDetectionLogEvent");
        zzcm zzcm8 = new zzcm();
        zzcm8.zza(5);
        zzi = builder8.withProperty(zzcm8.zzb()).build();
        FieldDescriptor.Builder builder9 = FieldDescriptor.builder("onDeviceFaceLoadLogEvent");
        zzcm zzcm9 = new zzcm();
        zzcm9.zza(59);
        zzj = builder9.withProperty(zzcm9.zzb()).build();
        FieldDescriptor.Builder builder10 = FieldDescriptor.builder("onDeviceTextDetectionLogEvent");
        zzcm zzcm10 = new zzcm();
        zzcm10.zza(6);
        zzk = builder10.withProperty(zzcm10.zzb()).build();
        FieldDescriptor.Builder builder11 = FieldDescriptor.builder("onDeviceBarcodeDetectionLogEvent");
        zzcm zzcm11 = new zzcm();
        zzcm11.zza(7);
        zzl = builder11.withProperty(zzcm11.zzb()).build();
        FieldDescriptor.Builder builder12 = FieldDescriptor.builder("onDeviceBarcodeLoadLogEvent");
        zzcm zzcm12 = new zzcm();
        zzcm12.zza(58);
        zzm = builder12.withProperty(zzcm12.zzb()).build();
        FieldDescriptor.Builder builder13 = FieldDescriptor.builder("onDeviceImageLabelCreateLogEvent");
        zzcm zzcm13 = new zzcm();
        zzcm13.zza(48);
        zzn = builder13.withProperty(zzcm13.zzb()).build();
        FieldDescriptor.Builder builder14 = FieldDescriptor.builder("onDeviceImageLabelLoadLogEvent");
        zzcm zzcm14 = new zzcm();
        zzcm14.zza(49);
        zzo = builder14.withProperty(zzcm14.zzb()).build();
        FieldDescriptor.Builder builder15 = FieldDescriptor.builder("onDeviceImageLabelDetectionLogEvent");
        zzcm zzcm15 = new zzcm();
        zzcm15.zza(18);
        zzp = builder15.withProperty(zzcm15.zzb()).build();
        FieldDescriptor.Builder builder16 = FieldDescriptor.builder("onDeviceObjectCreateLogEvent");
        zzcm zzcm16 = new zzcm();
        zzcm16.zza(26);
        zzq = builder16.withProperty(zzcm16.zzb()).build();
        FieldDescriptor.Builder builder17 = FieldDescriptor.builder("onDeviceObjectLoadLogEvent");
        zzcm zzcm17 = new zzcm();
        zzcm17.zza(27);
        zzr = builder17.withProperty(zzcm17.zzb()).build();
        FieldDescriptor.Builder builder18 = FieldDescriptor.builder("onDeviceObjectInferenceLogEvent");
        zzcm zzcm18 = new zzcm();
        zzcm18.zza(28);
        zzs = builder18.withProperty(zzcm18.zzb()).build();
        FieldDescriptor.Builder builder19 = FieldDescriptor.builder("onDevicePoseDetectionLogEvent");
        zzcm zzcm19 = new zzcm();
        zzcm19.zza(44);
        zzt = builder19.withProperty(zzcm19.zzb()).build();
        FieldDescriptor.Builder builder20 = FieldDescriptor.builder("onDeviceSegmentationLogEvent");
        zzcm zzcm20 = new zzcm();
        zzcm20.zza(45);
        zzu = builder20.withProperty(zzcm20.zzb()).build();
        FieldDescriptor.Builder builder21 = FieldDescriptor.builder("onDeviceSmartReplyLogEvent");
        zzcm zzcm21 = new zzcm();
        zzcm21.zza(19);
        zzv = builder21.withProperty(zzcm21.zzb()).build();
        FieldDescriptor.Builder builder22 = FieldDescriptor.builder("onDeviceLanguageIdentificationLogEvent");
        zzcm zzcm22 = new zzcm();
        zzcm22.zza(21);
        zzw = builder22.withProperty(zzcm22.zzb()).build();
        FieldDescriptor.Builder builder23 = FieldDescriptor.builder("onDeviceTranslationLogEvent");
        zzcm zzcm23 = new zzcm();
        zzcm23.zza(22);
        zzx = builder23.withProperty(zzcm23.zzb()).build();
        FieldDescriptor.Builder builder24 = FieldDescriptor.builder("cloudFaceDetectionLogEvent");
        zzcm zzcm24 = new zzcm();
        zzcm24.zza(8);
        zzy = builder24.withProperty(zzcm24.zzb()).build();
        FieldDescriptor.Builder builder25 = FieldDescriptor.builder("cloudCropHintDetectionLogEvent");
        zzcm zzcm25 = new zzcm();
        zzcm25.zza(9);
        zzz = builder25.withProperty(zzcm25.zzb()).build();
        FieldDescriptor.Builder builder26 = FieldDescriptor.builder("cloudDocumentTextDetectionLogEvent");
        zzcm zzcm26 = new zzcm();
        zzcm26.zza(10);
        zzA = builder26.withProperty(zzcm26.zzb()).build();
        FieldDescriptor.Builder builder27 = FieldDescriptor.builder("cloudImagePropertiesDetectionLogEvent");
        zzcm zzcm27 = new zzcm();
        zzcm27.zza(11);
        zzB = builder27.withProperty(zzcm27.zzb()).build();
        FieldDescriptor.Builder builder28 = FieldDescriptor.builder("cloudImageLabelDetectionLogEvent");
        zzcm zzcm28 = new zzcm();
        zzcm28.zza(12);
        zzC = builder28.withProperty(zzcm28.zzb()).build();
        FieldDescriptor.Builder builder29 = FieldDescriptor.builder("cloudLandmarkDetectionLogEvent");
        zzcm zzcm29 = new zzcm();
        zzcm29.zza(13);
        zzD = builder29.withProperty(zzcm29.zzb()).build();
        FieldDescriptor.Builder builder30 = FieldDescriptor.builder("cloudLogoDetectionLogEvent");
        zzcm zzcm30 = new zzcm();
        zzcm30.zza(14);
        zzE = builder30.withProperty(zzcm30.zzb()).build();
        FieldDescriptor.Builder builder31 = FieldDescriptor.builder("cloudSafeSearchDetectionLogEvent");
        zzcm zzcm31 = new zzcm();
        zzcm31.zza(15);
        zzF = builder31.withProperty(zzcm31.zzb()).build();
        FieldDescriptor.Builder builder32 = FieldDescriptor.builder("cloudTextDetectionLogEvent");
        zzcm zzcm32 = new zzcm();
        zzcm32.zza(16);
        zzG = builder32.withProperty(zzcm32.zzb()).build();
        FieldDescriptor.Builder builder33 = FieldDescriptor.builder("cloudWebSearchDetectionLogEvent");
        zzcm zzcm33 = new zzcm();
        zzcm33.zza(17);
        zzH = builder33.withProperty(zzcm33.zzb()).build();
        FieldDescriptor.Builder builder34 = FieldDescriptor.builder("automlImageLabelingCreateLogEvent");
        zzcm zzcm34 = new zzcm();
        zzcm34.zza(23);
        zzI = builder34.withProperty(zzcm34.zzb()).build();
        FieldDescriptor.Builder builder35 = FieldDescriptor.builder("automlImageLabelingLoadLogEvent");
        zzcm zzcm35 = new zzcm();
        zzcm35.zza(24);
        zzJ = builder35.withProperty(zzcm35.zzb()).build();
        FieldDescriptor.Builder builder36 = FieldDescriptor.builder("automlImageLabelingInferenceLogEvent");
        zzcm zzcm36 = new zzcm();
        zzcm36.zza(25);
        zzK = builder36.withProperty(zzcm36.zzb()).build();
        FieldDescriptor.Builder builder37 = FieldDescriptor.builder("isModelDownloadedLogEvent");
        zzcm zzcm37 = new zzcm();
        zzcm37.zza(39);
        zzL = builder37.withProperty(zzcm37.zzb()).build();
        FieldDescriptor.Builder builder38 = FieldDescriptor.builder("deleteModelLogEvent");
        zzcm zzcm38 = new zzcm();
        zzcm38.zza(40);
        zzM = builder38.withProperty(zzcm38.zzb()).build();
        FieldDescriptor.Builder builder39 = FieldDescriptor.builder("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzcm zzcm39 = new zzcm();
        zzcm39.zza(30);
        zzN = builder39.withProperty(zzcm39.zzb()).build();
        FieldDescriptor.Builder builder40 = FieldDescriptor.builder("aggregatedCustomModelInferenceLogEvent");
        zzcm zzcm40 = new zzcm();
        zzcm40.zza(31);
        zzO = builder40.withProperty(zzcm40.zzb()).build();
        FieldDescriptor.Builder builder41 = FieldDescriptor.builder("aggregatedOnDeviceFaceDetectionLogEvent");
        zzcm zzcm41 = new zzcm();
        zzcm41.zza(32);
        zzP = builder41.withProperty(zzcm41.zzb()).build();
        FieldDescriptor.Builder builder42 = FieldDescriptor.builder("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzcm zzcm42 = new zzcm();
        zzcm42.zza(33);
        zzQ = builder42.withProperty(zzcm42.zzb()).build();
        FieldDescriptor.Builder builder43 = FieldDescriptor.builder("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzcm zzcm43 = new zzcm();
        zzcm43.zza(34);
        zzR = builder43.withProperty(zzcm43.zzb()).build();
        FieldDescriptor.Builder builder44 = FieldDescriptor.builder("aggregatedOnDeviceObjectInferenceLogEvent");
        zzcm zzcm44 = new zzcm();
        zzcm44.zza(35);
        zzS = builder44.withProperty(zzcm44.zzb()).build();
        FieldDescriptor.Builder builder45 = FieldDescriptor.builder("aggregatedOnDeviceTextDetectionLogEvent");
        zzcm zzcm45 = new zzcm();
        zzcm45.zza(36);
        zzT = builder45.withProperty(zzcm45.zzb()).build();
        FieldDescriptor.Builder builder46 = FieldDescriptor.builder("aggregatedOnDevicePoseDetectionLogEvent");
        zzcm zzcm46 = new zzcm();
        zzcm46.zza(46);
        zzU = builder46.withProperty(zzcm46.zzb()).build();
        FieldDescriptor.Builder builder47 = FieldDescriptor.builder("aggregatedOnDeviceSegmentationLogEvent");
        zzcm zzcm47 = new zzcm();
        zzcm47.zza(47);
        zzV = builder47.withProperty(zzcm47.zzb()).build();
        FieldDescriptor.Builder builder48 = FieldDescriptor.builder("remoteConfigLogEvent");
        zzcm zzcm48 = new zzcm();
        zzcm48.zza(42);
        zzW = builder48.withProperty(zzcm48.zzb()).build();
        FieldDescriptor.Builder builder49 = FieldDescriptor.builder("inputImageConstructionLogEvent");
        zzcm zzcm49 = new zzcm();
        zzcm49.zza(50);
        zzX = builder49.withProperty(zzcm49.zzb()).build();
        FieldDescriptor.Builder builder50 = FieldDescriptor.builder("leakedHandleEvent");
        zzcm zzcm50 = new zzcm();
        zzcm50.zza(51);
        zzY = builder50.withProperty(zzcm50.zzb()).build();
        FieldDescriptor.Builder builder51 = FieldDescriptor.builder("cameraSourceLogEvent");
        zzcm zzcm51 = new zzcm();
        zzcm51.zza(52);
        zzZ = builder51.withProperty(zzcm51.zzb()).build();
        FieldDescriptor.Builder builder52 = FieldDescriptor.builder("imageLabelOptionalModuleLogEvent");
        zzcm zzcm52 = new zzcm();
        zzcm52.zza(53);
        zzaa = builder52.withProperty(zzcm52.zzb()).build();
        FieldDescriptor.Builder builder53 = FieldDescriptor.builder("languageIdentificationOptionalModuleLogEvent");
        zzcm zzcm53 = new zzcm();
        zzcm53.zza(54);
        zzab = builder53.withProperty(zzcm53.zzb()).build();
        FieldDescriptor.Builder builder54 = FieldDescriptor.builder("faceDetectionOptionalModuleLogEvent");
        zzcm zzcm54 = new zzcm();
        zzcm54.zza(60);
        zzac = builder54.withProperty(zzcm54.zzb()).build();
        FieldDescriptor.Builder builder55 = FieldDescriptor.builder("nlClassifierOptionalModuleLogEvent");
        zzcm zzcm55 = new zzcm();
        zzcm55.zza(55);
        zzad = builder55.withProperty(zzcm55.zzb()).build();
        FieldDescriptor.Builder builder56 = FieldDescriptor.builder("nlClassifierClientLibraryLogEvent");
        zzcm zzcm56 = new zzcm();
        zzcm56.zza(56);
        zzae = builder56.withProperty(zzcm56.zzb()).build();
        FieldDescriptor.Builder builder57 = FieldDescriptor.builder("accelerationAllowlistLogEvent");
        zzcm zzcm57 = new zzcm();
        zzcm57.zza(57);
        zzaf = builder57.withProperty(zzcm57.zzb()).build();
    }

    private zzfw() {
    }

    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) throws IOException {
        zziv zziv = (zziv) obj;
        ObjectEncoderContext objectEncoderContext = (ObjectEncoderContext) obj2;
        objectEncoderContext.add(zzb, (Object) zziv.zzd());
        objectEncoderContext.add(zzc, (Object) zziv.zzb());
        objectEncoderContext.add(zzd, (Object) zziv.zze());
        objectEncoderContext.add(zze, (Object) null);
        objectEncoderContext.add(zzf, (Object) null);
        objectEncoderContext.add(zzg, (Object) null);
        objectEncoderContext.add(zzh, (Object) null);
        objectEncoderContext.add(zzi, (Object) null);
        objectEncoderContext.add(zzj, (Object) null);
        objectEncoderContext.add(zzk, (Object) zziv.zzc());
        objectEncoderContext.add(zzl, (Object) null);
        objectEncoderContext.add(zzm, (Object) null);
        objectEncoderContext.add(zzn, (Object) null);
        objectEncoderContext.add(zzo, (Object) null);
        objectEncoderContext.add(zzp, (Object) null);
        objectEncoderContext.add(zzq, (Object) null);
        objectEncoderContext.add(zzr, (Object) null);
        objectEncoderContext.add(zzs, (Object) null);
        objectEncoderContext.add(zzt, (Object) null);
        objectEncoderContext.add(zzu, (Object) null);
        objectEncoderContext.add(zzv, (Object) null);
        objectEncoderContext.add(zzw, (Object) null);
        objectEncoderContext.add(zzx, (Object) null);
        objectEncoderContext.add(zzy, (Object) null);
        objectEncoderContext.add(zzz, (Object) null);
        objectEncoderContext.add(zzA, (Object) null);
        objectEncoderContext.add(zzB, (Object) null);
        objectEncoderContext.add(zzC, (Object) null);
        objectEncoderContext.add(zzD, (Object) null);
        objectEncoderContext.add(zzE, (Object) null);
        objectEncoderContext.add(zzF, (Object) null);
        objectEncoderContext.add(zzG, (Object) null);
        objectEncoderContext.add(zzH, (Object) null);
        objectEncoderContext.add(zzI, (Object) null);
        objectEncoderContext.add(zzJ, (Object) null);
        objectEncoderContext.add(zzK, (Object) null);
        objectEncoderContext.add(zzL, (Object) null);
        objectEncoderContext.add(zzM, (Object) null);
        objectEncoderContext.add(zzN, (Object) null);
        objectEncoderContext.add(zzO, (Object) null);
        objectEncoderContext.add(zzP, (Object) null);
        objectEncoderContext.add(zzQ, (Object) null);
        objectEncoderContext.add(zzR, (Object) null);
        objectEncoderContext.add(zzS, (Object) null);
        objectEncoderContext.add(zzT, (Object) zziv.zza());
        objectEncoderContext.add(zzU, (Object) null);
        objectEncoderContext.add(zzV, (Object) null);
        objectEncoderContext.add(zzW, (Object) null);
        objectEncoderContext.add(zzX, (Object) null);
        objectEncoderContext.add(zzY, (Object) null);
        objectEncoderContext.add(zzZ, (Object) null);
        objectEncoderContext.add(zzaa, (Object) null);
        objectEncoderContext.add(zzab, (Object) null);
        objectEncoderContext.add(zzac, (Object) null);
        objectEncoderContext.add(zzad, (Object) null);
        objectEncoderContext.add(zzae, (Object) null);
        objectEncoderContext.add(zzaf, (Object) null);
    }
}
