//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stropts.h>
#include <sys/socket.h>
#include <unistd.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// --------------------- Global Variables ---------------------

char * g1 = "\x1b\x5b\x31\x3b\x33\x36\x6d";
char * g2 = "\x2a\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\xc2\xa9\x20\x32\x30\x31\x38\x20\x4d\x61\x72\x6b\x75\x73\x20\x49\x70\x70\x79\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x2a";
char * g3 = "\x1b\x5b\x30\x6d";
char * g4 = "\x1b\x5b\x33\x33\x6d\x4c\x69\x63\x65\x6e\x63\x65\x20\x52\x65\x71\x75\x65\x73\x74\x20\x66\x69\x6c\x65\x20\x4c\x69\x63\x65\x6e\x63\x65\x20\x2d\x2d\x2d\x4c\x69\x63\x72\x65\x71\x75\x65\x73\x74\x2e\x6c\x69\x63\x2d\x2d\x2d\x20\x63\x72\x65\x61\x74\x65\x64\x20";
int32_t g5;

// ------------------------ Functions -------------------------

// Address range: 0x105f8 - 0x10924
int main(int argc, char ** argv) {
    // 0x105f8
    printf((char *)&g1);
    puts("**********************************************************************************");
    puts("*                            PowerTune UDP Daemon                                *");
    puts("*                              Licence Request                                   *");
    puts("*                                Version 1.0                                     *");
    puts((char *)&g2);
    puts("*                                                                                *");
    puts("*                    THIS SOFTWARE IS PROVIDED BY THE AUTHOR                     *");
    puts("* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,INCLUDING, BUT NOT LIMITED TO, *");
    puts("* THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE *");
    puts("* ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,         *");
    puts("* INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES             *");
    puts("* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;   *");
    puts("* LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND    *");
    puts("* ON ANY THEORY OF LIABILITY,WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT      *");
    puts("* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS  *");
    puts("* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.                   *");
    puts("*              Use of this software is strictly for PowerTune.                   *");
    puts("* The distribution and sale of this Software is exclusive to the copyright       *");
    puts("*                        owner and his affilliates.                              *");
    puts("*      To purchase a legal copy ,please email Markus.Ippy1981@gmail.com          *");
    puts("**********************************************************************************");
    printf((char *)&g3);
    int32_t sock_fd = socket(AF_INET, SOCK_DGRAM, IPPROTO_IP); // 0x106c8
    int32_t str; // bp-52
    strncpy((char *)&str, "eth0", 15);
    ioctl(sock_fd, 0x8927);
    close(sock_fd);
    struct _IO_FILE * file = fopen("Licrequest.lic", "w+"); // 0x10720
    unsigned char v1;
    int32_t v2 = v1; // 0x10728
    fprintf(file, "0x%02X", v2 + 6);
    fputc(44, file);
    unsigned char v3;
    int32_t v4 = v3; // 0x1074c
    fprintf(file, "0x%02X", v4 + 6);
    fputc(44, file);
    unsigned char v5;
    int32_t v6 = v5; // 0x10770
    int32_t v7 = v6 + 6; // 0x10774
    fprintf(file, "0x%02X", v7);
    fputc(44, file);
    fprintf(file, "0x%02X", v2 + 3);
    fputc(44, file);
    unsigned char v8;
    int32_t v9 = v8; // 0x107b8
    fprintf(file, "0x%02X", v9 + 3);
    fputc(44, file);
    unsigned char v10;
    fprintf(file, "0x%02X", (int32_t)v10 + 3);
    fputc(44, file);
    unsigned char v11;
    int32_t v12 = v11; // 0x10800
    fprintf(file, "0x%02X", v12 + 3);
    fputc(44, file);
    fprintf(file, "0x%02X", v6 + 3);
    fputc(44, file);
    fprintf(file, "0x%02X", v4 + 3);
    fputc(44, file);
    fprintf(file, "0x%02X", v9 + 6);
    fputc(44, file);
    fprintf(file, "0x%02X", v12 + 1);
    fputc(44, file);
    fprintf(file, "0x%02X", v7);
    fputc(44, file);
    fprintf(file, "0x%02X", v4 + 2);
    fputc(44, file);
    fprintf(file, "0x%02X", v2 + 2);
    puts((char *)&g4);
    exit(1);
    return &g5;
}

// --------------- Dynamically Linked Functions ---------------

// int close(int fd);
// void exit(int status);
// FILE * fopen(const char * restrict filename, const char * restrict modes);
// int fprintf(FILE * restrict stream, const char * restrict format, ...);
// int fputc(int c, FILE * stream);
// int ioctl(int fd, unsigned long int request, ...);
// int printf(const char * restrict format, ...);
// int puts(const char * s);
// int socket(int domain, int type, int protocol);
// char * strncpy(char * restrict dest, const char * restrict src, size_t n);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (6.3.0)
// Detected functions: 1
// Decompilation date: 2019-03-26 06:58:54
