package com.google.android.gms.internal.mlkit_vision_common;

import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import java.io.IOException;

/* compiled from: com.google.mlkit:vision-common@@16.5.0 */
final class zzda implements ObjectEncoder<zzfv> {
    private static final FieldDescriptor zzA;
    private static final FieldDescriptor zzB;
    private static final FieldDescriptor zzC;
    private static final FieldDescriptor zzD;
    private static final FieldDescriptor zzE;
    private static final FieldDescriptor zzF;
    private static final FieldDescriptor zzG;
    private static final FieldDescriptor zzH;
    private static final FieldDescriptor zzI;
    private static final FieldDescriptor zzJ;
    private static final FieldDescriptor zzK;
    private static final FieldDescriptor zzL;
    private static final FieldDescriptor zzM;
    private static final FieldDescriptor zzN;
    private static final FieldDescriptor zzO;
    private static final FieldDescriptor zzP;
    private static final FieldDescriptor zzQ;
    private static final FieldDescriptor zzR;
    private static final FieldDescriptor zzS;
    private static final FieldDescriptor zzT;
    private static final FieldDescriptor zzU;
    private static final FieldDescriptor zzV;
    private static final FieldDescriptor zzW;
    private static final FieldDescriptor zzX;
    private static final FieldDescriptor zzY;
    private static final FieldDescriptor zzZ;
    static final zzda zza = new zzda();
    private static final FieldDescriptor zzaa;
    private static final FieldDescriptor zzab;
    private static final FieldDescriptor zzac;
    private static final FieldDescriptor zzad;
    private static final FieldDescriptor zzae;
    private static final FieldDescriptor zzaf;
    private static final FieldDescriptor zzb;
    private static final FieldDescriptor zzc;
    private static final FieldDescriptor zzd;
    private static final FieldDescriptor zze;
    private static final FieldDescriptor zzf;
    private static final FieldDescriptor zzg;
    private static final FieldDescriptor zzh;
    private static final FieldDescriptor zzi;
    private static final FieldDescriptor zzj;
    private static final FieldDescriptor zzk;
    private static final FieldDescriptor zzl;
    private static final FieldDescriptor zzm;
    private static final FieldDescriptor zzn;
    private static final FieldDescriptor zzo;
    private static final FieldDescriptor zzp;
    private static final FieldDescriptor zzq;
    private static final FieldDescriptor zzr;
    private static final FieldDescriptor zzs;
    private static final FieldDescriptor zzt;
    private static final FieldDescriptor zzu;
    private static final FieldDescriptor zzv;
    private static final FieldDescriptor zzw;
    private static final FieldDescriptor zzx;
    private static final FieldDescriptor zzy;
    private static final FieldDescriptor zzz;

    static {
        FieldDescriptor.Builder builder = FieldDescriptor.builder("systemInfo");
        zzt zzt2 = new zzt();
        zzt2.zza(1);
        zzb = builder.withProperty(zzt2.zzb()).build();
        FieldDescriptor.Builder builder2 = FieldDescriptor.builder("eventName");
        zzt zzt3 = new zzt();
        zzt3.zza(2);
        zzc = builder2.withProperty(zzt3.zzb()).build();
        FieldDescriptor.Builder builder3 = FieldDescriptor.builder("isThickClient");
        zzt zzt4 = new zzt();
        zzt4.zza(37);
        zzd = builder3.withProperty(zzt4.zzb()).build();
        FieldDescriptor.Builder builder4 = FieldDescriptor.builder("modelDownloadLogEvent");
        zzt zzt5 = new zzt();
        zzt5.zza(3);
        zze = builder4.withProperty(zzt5.zzb()).build();
        FieldDescriptor.Builder builder5 = FieldDescriptor.builder("customModelLoadLogEvent");
        zzt zzt6 = new zzt();
        zzt6.zza(20);
        zzf = builder5.withProperty(zzt6.zzb()).build();
        FieldDescriptor.Builder builder6 = FieldDescriptor.builder("customModelInferenceLogEvent");
        zzt zzt7 = new zzt();
        zzt7.zza(4);
        zzg = builder6.withProperty(zzt7.zzb()).build();
        FieldDescriptor.Builder builder7 = FieldDescriptor.builder("customModelCreateLogEvent");
        zzt zzt8 = new zzt();
        zzt8.zza(29);
        zzh = builder7.withProperty(zzt8.zzb()).build();
        FieldDescriptor.Builder builder8 = FieldDescriptor.builder("onDeviceFaceDetectionLogEvent");
        zzt zzt9 = new zzt();
        zzt9.zza(5);
        zzi = builder8.withProperty(zzt9.zzb()).build();
        FieldDescriptor.Builder builder9 = FieldDescriptor.builder("onDeviceFaceLoadLogEvent");
        zzt zzt10 = new zzt();
        zzt10.zza(59);
        zzj = builder9.withProperty(zzt10.zzb()).build();
        FieldDescriptor.Builder builder10 = FieldDescriptor.builder("onDeviceTextDetectionLogEvent");
        zzt zzt11 = new zzt();
        zzt11.zza(6);
        zzk = builder10.withProperty(zzt11.zzb()).build();
        FieldDescriptor.Builder builder11 = FieldDescriptor.builder("onDeviceBarcodeDetectionLogEvent");
        zzt zzt12 = new zzt();
        zzt12.zza(7);
        zzl = builder11.withProperty(zzt12.zzb()).build();
        FieldDescriptor.Builder builder12 = FieldDescriptor.builder("onDeviceBarcodeLoadLogEvent");
        zzt zzt13 = new zzt();
        zzt13.zza(58);
        zzm = builder12.withProperty(zzt13.zzb()).build();
        FieldDescriptor.Builder builder13 = FieldDescriptor.builder("onDeviceImageLabelCreateLogEvent");
        zzt zzt14 = new zzt();
        zzt14.zza(48);
        zzn = builder13.withProperty(zzt14.zzb()).build();
        FieldDescriptor.Builder builder14 = FieldDescriptor.builder("onDeviceImageLabelLoadLogEvent");
        zzt zzt15 = new zzt();
        zzt15.zza(49);
        zzo = builder14.withProperty(zzt15.zzb()).build();
        FieldDescriptor.Builder builder15 = FieldDescriptor.builder("onDeviceImageLabelDetectionLogEvent");
        zzt zzt16 = new zzt();
        zzt16.zza(18);
        zzp = builder15.withProperty(zzt16.zzb()).build();
        FieldDescriptor.Builder builder16 = FieldDescriptor.builder("onDeviceObjectCreateLogEvent");
        zzt zzt17 = new zzt();
        zzt17.zza(26);
        zzq = builder16.withProperty(zzt17.zzb()).build();
        FieldDescriptor.Builder builder17 = FieldDescriptor.builder("onDeviceObjectLoadLogEvent");
        zzt zzt18 = new zzt();
        zzt18.zza(27);
        zzr = builder17.withProperty(zzt18.zzb()).build();
        FieldDescriptor.Builder builder18 = FieldDescriptor.builder("onDeviceObjectInferenceLogEvent");
        zzt zzt19 = new zzt();
        zzt19.zza(28);
        zzs = builder18.withProperty(zzt19.zzb()).build();
        FieldDescriptor.Builder builder19 = FieldDescriptor.builder("onDevicePoseDetectionLogEvent");
        zzt zzt20 = new zzt();
        zzt20.zza(44);
        zzt = builder19.withProperty(zzt20.zzb()).build();
        FieldDescriptor.Builder builder20 = FieldDescriptor.builder("onDeviceSegmentationLogEvent");
        zzt zzt21 = new zzt();
        zzt21.zza(45);
        zzu = builder20.withProperty(zzt21.zzb()).build();
        FieldDescriptor.Builder builder21 = FieldDescriptor.builder("onDeviceSmartReplyLogEvent");
        zzt zzt22 = new zzt();
        zzt22.zza(19);
        zzv = builder21.withProperty(zzt22.zzb()).build();
        FieldDescriptor.Builder builder22 = FieldDescriptor.builder("onDeviceLanguageIdentificationLogEvent");
        zzt zzt23 = new zzt();
        zzt23.zza(21);
        zzw = builder22.withProperty(zzt23.zzb()).build();
        FieldDescriptor.Builder builder23 = FieldDescriptor.builder("onDeviceTranslationLogEvent");
        zzt zzt24 = new zzt();
        zzt24.zza(22);
        zzx = builder23.withProperty(zzt24.zzb()).build();
        FieldDescriptor.Builder builder24 = FieldDescriptor.builder("cloudFaceDetectionLogEvent");
        zzt zzt25 = new zzt();
        zzt25.zza(8);
        zzy = builder24.withProperty(zzt25.zzb()).build();
        FieldDescriptor.Builder builder25 = FieldDescriptor.builder("cloudCropHintDetectionLogEvent");
        zzt zzt26 = new zzt();
        zzt26.zza(9);
        zzz = builder25.withProperty(zzt26.zzb()).build();
        FieldDescriptor.Builder builder26 = FieldDescriptor.builder("cloudDocumentTextDetectionLogEvent");
        zzt zzt27 = new zzt();
        zzt27.zza(10);
        zzA = builder26.withProperty(zzt27.zzb()).build();
        FieldDescriptor.Builder builder27 = FieldDescriptor.builder("cloudImagePropertiesDetectionLogEvent");
        zzt zzt28 = new zzt();
        zzt28.zza(11);
        zzB = builder27.withProperty(zzt28.zzb()).build();
        FieldDescriptor.Builder builder28 = FieldDescriptor.builder("cloudImageLabelDetectionLogEvent");
        zzt zzt29 = new zzt();
        zzt29.zza(12);
        zzC = builder28.withProperty(zzt29.zzb()).build();
        FieldDescriptor.Builder builder29 = FieldDescriptor.builder("cloudLandmarkDetectionLogEvent");
        zzt zzt30 = new zzt();
        zzt30.zza(13);
        zzD = builder29.withProperty(zzt30.zzb()).build();
        FieldDescriptor.Builder builder30 = FieldDescriptor.builder("cloudLogoDetectionLogEvent");
        zzt zzt31 = new zzt();
        zzt31.zza(14);
        zzE = builder30.withProperty(zzt31.zzb()).build();
        FieldDescriptor.Builder builder31 = FieldDescriptor.builder("cloudSafeSearchDetectionLogEvent");
        zzt zzt32 = new zzt();
        zzt32.zza(15);
        zzF = builder31.withProperty(zzt32.zzb()).build();
        FieldDescriptor.Builder builder32 = FieldDescriptor.builder("cloudTextDetectionLogEvent");
        zzt zzt33 = new zzt();
        zzt33.zza(16);
        zzG = builder32.withProperty(zzt33.zzb()).build();
        FieldDescriptor.Builder builder33 = FieldDescriptor.builder("cloudWebSearchDetectionLogEvent");
        zzt zzt34 = new zzt();
        zzt34.zza(17);
        zzH = builder33.withProperty(zzt34.zzb()).build();
        FieldDescriptor.Builder builder34 = FieldDescriptor.builder("automlImageLabelingCreateLogEvent");
        zzt zzt35 = new zzt();
        zzt35.zza(23);
        zzI = builder34.withProperty(zzt35.zzb()).build();
        FieldDescriptor.Builder builder35 = FieldDescriptor.builder("automlImageLabelingLoadLogEvent");
        zzt zzt36 = new zzt();
        zzt36.zza(24);
        zzJ = builder35.withProperty(zzt36.zzb()).build();
        FieldDescriptor.Builder builder36 = FieldDescriptor.builder("automlImageLabelingInferenceLogEvent");
        zzt zzt37 = new zzt();
        zzt37.zza(25);
        zzK = builder36.withProperty(zzt37.zzb()).build();
        FieldDescriptor.Builder builder37 = FieldDescriptor.builder("isModelDownloadedLogEvent");
        zzt zzt38 = new zzt();
        zzt38.zza(39);
        zzL = builder37.withProperty(zzt38.zzb()).build();
        FieldDescriptor.Builder builder38 = FieldDescriptor.builder("deleteModelLogEvent");
        zzt zzt39 = new zzt();
        zzt39.zza(40);
        zzM = builder38.withProperty(zzt39.zzb()).build();
        FieldDescriptor.Builder builder39 = FieldDescriptor.builder("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzt zzt40 = new zzt();
        zzt40.zza(30);
        zzN = builder39.withProperty(zzt40.zzb()).build();
        FieldDescriptor.Builder builder40 = FieldDescriptor.builder("aggregatedCustomModelInferenceLogEvent");
        zzt zzt41 = new zzt();
        zzt41.zza(31);
        zzO = builder40.withProperty(zzt41.zzb()).build();
        FieldDescriptor.Builder builder41 = FieldDescriptor.builder("aggregatedOnDeviceFaceDetectionLogEvent");
        zzt zzt42 = new zzt();
        zzt42.zza(32);
        zzP = builder41.withProperty(zzt42.zzb()).build();
        FieldDescriptor.Builder builder42 = FieldDescriptor.builder("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzt zzt43 = new zzt();
        zzt43.zza(33);
        zzQ = builder42.withProperty(zzt43.zzb()).build();
        FieldDescriptor.Builder builder43 = FieldDescriptor.builder("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzt zzt44 = new zzt();
        zzt44.zza(34);
        zzR = builder43.withProperty(zzt44.zzb()).build();
        FieldDescriptor.Builder builder44 = FieldDescriptor.builder("aggregatedOnDeviceObjectInferenceLogEvent");
        zzt zzt45 = new zzt();
        zzt45.zza(35);
        zzS = builder44.withProperty(zzt45.zzb()).build();
        FieldDescriptor.Builder builder45 = FieldDescriptor.builder("aggregatedOnDeviceTextDetectionLogEvent");
        zzt zzt46 = new zzt();
        zzt46.zza(36);
        zzT = builder45.withProperty(zzt46.zzb()).build();
        FieldDescriptor.Builder builder46 = FieldDescriptor.builder("aggregatedOnDevicePoseDetectionLogEvent");
        zzt zzt47 = new zzt();
        zzt47.zza(46);
        zzU = builder46.withProperty(zzt47.zzb()).build();
        FieldDescriptor.Builder builder47 = FieldDescriptor.builder("aggregatedOnDeviceSegmentationLogEvent");
        zzt zzt48 = new zzt();
        zzt48.zza(47);
        zzV = builder47.withProperty(zzt48.zzb()).build();
        FieldDescriptor.Builder builder48 = FieldDescriptor.builder("remoteConfigLogEvent");
        zzt zzt49 = new zzt();
        zzt49.zza(42);
        zzW = builder48.withProperty(zzt49.zzb()).build();
        FieldDescriptor.Builder builder49 = FieldDescriptor.builder("inputImageConstructionLogEvent");
        zzt zzt50 = new zzt();
        zzt50.zza(50);
        zzX = builder49.withProperty(zzt50.zzb()).build();
        FieldDescriptor.Builder builder50 = FieldDescriptor.builder("leakedHandleEvent");
        zzt zzt51 = new zzt();
        zzt51.zza(51);
        zzY = builder50.withProperty(zzt51.zzb()).build();
        FieldDescriptor.Builder builder51 = FieldDescriptor.builder("cameraSourceLogEvent");
        zzt zzt52 = new zzt();
        zzt52.zza(52);
        zzZ = builder51.withProperty(zzt52.zzb()).build();
        FieldDescriptor.Builder builder52 = FieldDescriptor.builder("imageLabelOptionalModuleLogEvent");
        zzt zzt53 = new zzt();
        zzt53.zza(53);
        zzaa = builder52.withProperty(zzt53.zzb()).build();
        FieldDescriptor.Builder builder53 = FieldDescriptor.builder("languageIdentificationOptionalModuleLogEvent");
        zzt zzt54 = new zzt();
        zzt54.zza(54);
        zzab = builder53.withProperty(zzt54.zzb()).build();
        FieldDescriptor.Builder builder54 = FieldDescriptor.builder("faceDetectionOptionalModuleLogEvent");
        zzt zzt55 = new zzt();
        zzt55.zza(60);
        zzac = builder54.withProperty(zzt55.zzb()).build();
        FieldDescriptor.Builder builder55 = FieldDescriptor.builder("nlClassifierOptionalModuleLogEvent");
        zzt zzt56 = new zzt();
        zzt56.zza(55);
        zzad = builder55.withProperty(zzt56.zzb()).build();
        FieldDescriptor.Builder builder56 = FieldDescriptor.builder("nlClassifierClientLibraryLogEvent");
        zzt zzt57 = new zzt();
        zzt57.zza(56);
        zzae = builder56.withProperty(zzt57.zzb()).build();
        FieldDescriptor.Builder builder57 = FieldDescriptor.builder("accelerationAllowlistLogEvent");
        zzt zzt58 = new zzt();
        zzt58.zza(57);
        zzaf = builder57.withProperty(zzt58.zzb()).build();
    }

    private zzda() {
    }

    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) throws IOException {
        zzfv zzfv = (zzfv) obj;
        ObjectEncoderContext objectEncoderContext = (ObjectEncoderContext) obj2;
        objectEncoderContext.add(zzb, (Object) zzfv.zzc());
        objectEncoderContext.add(zzc, (Object) zzfv.zzb());
        objectEncoderContext.add(zzd, (Object) null);
        objectEncoderContext.add(zze, (Object) null);
        objectEncoderContext.add(zzf, (Object) null);
        objectEncoderContext.add(zzg, (Object) null);
        objectEncoderContext.add(zzh, (Object) null);
        objectEncoderContext.add(zzi, (Object) null);
        objectEncoderContext.add(zzj, (Object) null);
        objectEncoderContext.add(zzk, (Object) null);
        objectEncoderContext.add(zzl, (Object) null);
        objectEncoderContext.add(zzm, (Object) null);
        objectEncoderContext.add(zzn, (Object) null);
        objectEncoderContext.add(zzo, (Object) null);
        objectEncoderContext.add(zzp, (Object) null);
        objectEncoderContext.add(zzq, (Object) null);
        objectEncoderContext.add(zzr, (Object) null);
        objectEncoderContext.add(zzs, (Object) null);
        objectEncoderContext.add(zzt, (Object) null);
        objectEncoderContext.add(zzu, (Object) null);
        objectEncoderContext.add(zzv, (Object) null);
        objectEncoderContext.add(zzw, (Object) null);
        objectEncoderContext.add(zzx, (Object) null);
        objectEncoderContext.add(zzy, (Object) null);
        objectEncoderContext.add(zzz, (Object) null);
        objectEncoderContext.add(zzA, (Object) null);
        objectEncoderContext.add(zzB, (Object) null);
        objectEncoderContext.add(zzC, (Object) null);
        objectEncoderContext.add(zzD, (Object) null);
        objectEncoderContext.add(zzE, (Object) null);
        objectEncoderContext.add(zzF, (Object) null);
        objectEncoderContext.add(zzG, (Object) null);
        objectEncoderContext.add(zzH, (Object) null);
        objectEncoderContext.add(zzI, (Object) null);
        objectEncoderContext.add(zzJ, (Object) null);
        objectEncoderContext.add(zzK, (Object) null);
        objectEncoderContext.add(zzL, (Object) null);
        objectEncoderContext.add(zzM, (Object) null);
        objectEncoderContext.add(zzN, (Object) null);
        objectEncoderContext.add(zzO, (Object) null);
        objectEncoderContext.add(zzP, (Object) null);
        objectEncoderContext.add(zzQ, (Object) null);
        objectEncoderContext.add(zzR, (Object) null);
        objectEncoderContext.add(zzS, (Object) null);
        objectEncoderContext.add(zzT, (Object) null);
        objectEncoderContext.add(zzU, (Object) null);
        objectEncoderContext.add(zzV, (Object) null);
        objectEncoderContext.add(zzW, (Object) null);
        objectEncoderContext.add(zzX, (Object) zzfv.zza());
        objectEncoderContext.add(zzY, (Object) null);
        objectEncoderContext.add(zzZ, (Object) null);
        objectEncoderContext.add(zzaa, (Object) null);
        objectEncoderContext.add(zzab, (Object) null);
        objectEncoderContext.add(zzac, (Object) null);
        objectEncoderContext.add(zzad, (Object) null);
        objectEncoderContext.add(zzae, (Object) null);
        objectEncoderContext.add(zzaf, (Object) null);
    }
}
